---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gimlet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gimlet
subjects:
  - kind: ServiceAccount
    name: gimlet
    namespace: gimlet
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: gimlet
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - nodes
      - pods
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: gimlet-leaderelection
  namespace: gimlet
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: gimlet-leaderelection
  namespace: gimlet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gimlet-leaderelection
subjects:
  - kind: ServiceAccount
    name: gimlet
    namespace: gimlet